import apiClient from "../../interceptor";

export const putUpdateUser = (
  id,
  fName,
  lName,
  userName,
  gmail,
  phoneNumber,
  active,
  isDelete,
  isTeacher,
  isStudent,
  recoveryEmail,
  twoStepAuth,
  userAbout,
  currentPictureAddress,
  linkdinProfile,
  telegramLink,
  receiveMessageEvent,
  homeAdderess,
  nationalCode,
  gender,
  latitude,
  longitude,
  insertDate,
  birthDay,
) => {
  return apiClient.put(
    "/User/UpdateUser",
    // {
    //   params: {
    //     query: null,
    //     perPage: null,
    //     page: null,
    //     isActive: active,
    //     tournamentId: null,
    //   },
    // },
    {
      id: id,
      fName: fName,
      lName: lName,
      userName: userName,
      gmail: gmail,
      phoneNumber: phoneNumber,
      active: active,
      isDelete: isDelete,
      isTecher: isTeacher,
      isStudent: isStudent,
      recoveryEmail: recoveryEmail,
      twoStepAuth: twoStepAuth,
      userAbout: userAbout,
      currentPictureAddress: currentPictureAddress,
      linkdinProfile: linkdinProfile,
      telegramLink: telegramLink,
      receiveMessageEvent: receiveMessageEvent,
      homeAdderess: homeAdderess,
      nationalCode: nationalCode,
      gender: gender,
      latitude: latitude,
      longitude: longitude,
      insertDate: insertDate,
      birthDay: birthDay,
    },
  );
};
