import {
  Mail,
  Home,
  MessageSquare,
  Calendar,
  Airplay,
  Circle,
  FileText,
  Book,
  FilePlus,
  Archive,
  Tool,
  Bookmark,
  Briefcase,
  PenTool,
  Users,
  Share2,
  User,
  Settings,
  Menu,
} from "react-feather";

export default [
  {
    id: "eCommerceDash",
    title: "داشبورد",
    icon: <Home size={20} />,
    navLink: "/ecommerce",
  },
  {
    id: "userList",
    title: "مدیریت کاربران",
    icon: <User size={20} />,
    navLink: "/user/list",
  },
  {
    id: "commentsList",
    title: "کامنت ها",
    icon: <Bookmark size={20} />,
    navLink: "/comments/list",
  },
  {
    id: "calendar",
    title: "تقویم",
    icon: <Calendar />,
    navLink: "/apps/calendar",
  },
  {
    id: "chat",
    title: "تیکت پشتیبانی",
    icon: <MessageSquare />,
    navLink: "/apps/chat",
  },
  // {
  //   id: "secondPage",
  //   title: "Second Page",
  //   icon: <Mail size={20} />,
  //   navLink: "/second-page",
  // },
  // {
  //   id: "smaplePage",
  //   title: "Sample Page",
  //   icon: <Airplay size={20} />,
  //   // navLink: "/sample",
  //   children: [
  //     {
  //       id: "invoiceList",
  //       title: "List",
  //       icon: <Circle size={12} />,
  //       navLink: "/apps/invoice/list",
  //     },
  //   ],
  // },
  {
    id: "courses",
    title: "دوره ها",
    icon: <Archive style={{ width: 20, height: 20 }} />,
    children: [
      {
        id: "AllCourses",
        title: "دوره ها",
        icon: <Circle size={12} />,
        navLink: "/AllCourses",
      },
      {
        id: "updateCourses",
        title: "بروزرسانی دوره ها",
        icon: <Circle size={12} />,
        navLink: "/updateCourses",
      },
      // {
      //   id: "reservedCourse",
      //   title: "دوره های رزرو شده",
      //   icon: <Circle size={12} />,
      //   navLink: "/reservedCourse",
      // },
      {
        id: "techupdate",
        title: "تنظیمات دوره",
        icon: <Circle size={12} />,
        navLink: "/techupdate",
      },
      {
        id: "CourseHelps",
        title: "دوره های کمکی",
        icon: <Circle size={12} />,
        navLink: "/CourseHelps",
      },
      {
        id: "SocialGroup",
        title: "گروه های اجتماعی",
        icon: <Circle size={12} />,
        navLink: "/SocialGroup",
      },
      {
        id: "CourseGroup",
        title: "بروزرسانی گروه هایه دوره",
        icon: <Circle />,
        navLink: "/CourseGroup",
      },
      {
        id: "sessions",
        title: "جلسه ها",
        icon: <Menu />,
        navLink: "/sessions",
        children: [
          {
            id: "useHomework",
            title: "لیست تکالیف کاربران",
            icon: <Circle />,
            navLink: "/useHomework",
          },
          // {
          //   id: "updatejobs",
          //   title: "بروزرسانی مشاغل",
          //   icon: <Circle />,
          //   navLink: "/updatejobs",
          // },
        ],
      },
    ],
  },

  {
    id: "blogList",
    title: " وبلاگ ها",
    icon: <FileText size={20} />,
    permissions: ["admin", "editor"],
    navLink: "/pages/blog/list",
    children: [
      {
        id: "blogList",
        title: "لیست وبلاگ ها",
        icon: <Circle />,
        navLink: "/pages/blog/list",
      },
      {
        id: "blogEdit",
        title: "ایجاد وبلاگ ",
        icon: <Circle />,
        navLink: "/pages/blog/edit",
      },
      {
        id: "category",
        title: "لیست  دسته بندی ها",
        icon: <Circle size={12} />,
        navLink: "/pages/blog/category",
      },
      {
        id: "categoryEdit",
        title: "ایجاد دسته بندی جدید ",
        icon: <Circle />,
        navLink: "/pages/blog/add",
      },
    ],
  },
  {
    id: "Buildings",
    title: "  ساختمان ها و دپارتمان ها",
    icon: <Home size={20} />,
    permissions: ["admin", "editor"],
    navLink: "/pages/Buildings",
    children: [
      {
        id: "Buildings",
        title: "  مدیریت ساختمان ها  ",
        icon: <Circle size={20} />,
        navLink: "/pages/Buildings/list",
      },
      {
        id: "department",
        title: "  مدیریت  دپارتمان ها ",
        icon: <Circle size={12} />,
        navLink: "/pages/Buildings/department",
      },
      {
        id: "classroomManagement",
        title: "  مدیریت  کلاس  ها ",
        icon: <Circle size={12} />,
        navLink: "/pages/Buildings/ClassroomManagement",
      },
      {
        id: "TermManagement",
        title: "  مدیریت    ترم ها ",
        icon: <Circle size={12} />,
        navLink: "/pages/Buildings/TermManagement",
      },
    ],
  },
  {
    id: "jobs",
    title: "مشاغل",
    icon: <Briefcase size={20} />,
    children: [
      {
        id: "jobs",
        title: "تمام مشاغل",
        icon: <Circle size={12} />,
        navLink: "/jobs",
      },
      {
        id: "updatejobs",
        title: "بروزرسانی مشاغل",
        icon: <Circle size={12} />,
        navLink: "/updatejobs",
      },
    ],
  },

  // {
  //   id: "assistance",
  //   title: "مشاوران",
  //   icon: <PenTool style={{ width: 20, height: 20 }} />,
  //   navLink: "/assistance",
  // },
];
